// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFvyUq-MwZAGxLSxV648CdJ81FWxjtS7I',
    appId: '1:141654800582:web:81cae19e14ed5e04ffffc7',
    messagingSenderId: '141654800582',
    projectId: 'rexx-98ab0',
    authDomain: 'rexx-98ab0.firebaseapp.com',
    storageBucket: 'rexx-98ab0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcFwJiwNdNxem79NMgr3p7_j27iQukdUs',
    appId: '1:141654800582:android:c0f27101910859c7ffffc7',
    messagingSenderId: '141654800582',
    projectId: 'rexx-98ab0',
    storageBucket: 'rexx-98ab0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5Gp5ipHZpF-M4as3xlQVGof3-_UnBZSg',
    appId: '1:141654800582:ios:30d265f2f27572e8ffffc7',
    messagingSenderId: '141654800582',
    projectId: 'rexx-98ab0',
    storageBucket: 'rexx-98ab0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5Gp5ipHZpF-M4as3xlQVGof3-_UnBZSg',
    appId: '1:141654800582:ios:30d265f2f27572e8ffffc7',
    messagingSenderId: '141654800582',
    projectId: 'rexx-98ab0',
    storageBucket: 'rexx-98ab0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFvyUq-MwZAGxLSxV648CdJ81FWxjtS7I',
    appId: '1:141654800582:web:d075bf6a5e72cbf1ffffc7',
    messagingSenderId: '141654800582',
    projectId: 'rexx-98ab0',
    authDomain: 'rexx-98ab0.firebaseapp.com',
    storageBucket: 'rexx-98ab0.firebasestorage.app',
  );
}
